name: UpOnlyKB
version: '1.0.7'
main: jp.yoma.Main
api-version: '1.21'
authors: [ KozukiYOMA ]
description: RemoveUnderKB
commands:
  uponlykb:
    description: Reload config
    usage: /uponlykb reload
    permission: uponlykb.reload
    permission-message: §cYou have no permission
